name: Romeogoedel
favicon: null
layout_spectrum: 0.20941703766584396
typography_spectrum: 0.7779665202833712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6136822805274278
  lightness: 0.954610823886469
  saturation: 0.6701483419165015
  rhythmicContrast: 0.6521201136056334
purpose: []
